version: "3.3"
services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: yarn start:dev
    restart: always
