version: "3.3"
services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
      - "9229:9229"
    command: yarn start:dev
    depends_on:
      - mongo
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
